apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: webapp
    name: webapp
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: webapp
      deploymentconfig: webapp
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: webapp
    name: webapp
  spec:
    replicas: 1
    selector:
      app: webapp
      deploymentconfig: webapp
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: webapp
          deploymentconfig: webapp
      spec:
        containers:
        - image: 172.30.1.1:5000/moneyhack/webapp:latest
          name: webapp
          command: [ "bash" ]
          args: [ "-c", "yarn start" ]
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - webapp
        from:
          kind: ImageStreamTag
          name: webapp:latest
          namespace: moneyhack
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
kind: List
metadata: {}
